name: persistent_user_dir_access_android_example
description: "Demonstrates how to use the persistent_user_dir_access_android plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  persistent_user_dir_access_android:
    # When depending on this package from a real application you should use:
    #   persistent_user_dir_access_android: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

