name: 'Testing 🧪'
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  kotlin-tests:
    name: "[plugin] Android unit"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: beta
          cache: true
      - run: flutter config --no-analytics --suppress-analytics
      - uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"
          cache: 'gradle'
      - name: Build testing resources
        run: flutter build aab --debug
        working-directory: example
      - run: ./gradlew testDebugUnitTest --no-daemon
        working-directory: example/android
  plugin-unit-tests:
    name: "[plugin] Flutter unit"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: beta
          cache: true
      - run: flutter config --no-analytics --suppress-analytics
      - run: flutter test
  example-unit-tests:
    name: "[example] Flutter unit"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: beta
          cache: true
      - run: flutter config --no-analytics --suppress-analytics
      - run: flutter test
        working-directory: example